version: '3'

services:
  laravel_app:
    image: php:8-fpm
    volumes:
      - ./:/var/www/html
    networks:
      - app_network

  nginx:
    image: nginx:latest
    ports:
      - "38080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html
    depends_on:
      - laravel_app
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
